project_id = "eotfijnsfwroukhjwsbe"

[functions.send-sms]
verify_jwt = false

[functions.make-call]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.recording-callback]
verify_jwt = false

[functions.generate-call-recap]
verify_jwt = false
